name = "UnifiedPseudopotentialFormat"
uuid = "8030dd95-f9ed-4dd5-b230-99ba15524fc3"
authors = ["Reno <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
AcuteML = "6b84a0a3-a11a-41fa-a417-e600528de108"

[compat]
julia = "1"
AcuteML = "0.8, 0.9, 0.10, 0.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
